In [1]:
fixed_salary = [100,200,300]
variable_salary = [10,20,30]
total_salary = fixed_salary + variable_salary
print(total_salary)

[100, 200, 300, 10, 20, 30]


In [2]:
type(fixed_salary)

list

### Numpy For The Solution

In [3]:
import numpy as np

fixed = np.array(fixed_salary)
variable = np.array(variable_salary)
total = fixed + variable  # both has to be of the same size
print(total)

[110 220 330]


In [4]:
# Try all this with array
# l +-*/5
#l2 +-*/l
# Tell which worked

In [6]:
type(fixed)

numpy.ndarray

In [7]:
fixed

array([100, 200, 300])

In [8]:
variable

array([10, 20, 30])

In [9]:
type(total)        # ndarray - n-dimensional array

numpy.ndarray

In [5]:
total

array([110, 220, 330])

In [10]:
#Broadcasting / element wise
total+10

array([120, 230, 340])

In [11]:
#Broadcasting
total>200

array([False,  True,  True])

In [12]:
#Boolean Indexing
total[total>200]

array([220, 330])

In [13]:
total[total>200][1]

330

#### filter all even value and find the sq of each

In [14]:
ps=[2,3,4,5,6,7,8,9,10]
ps=np.array(ps)
ps_eve=ps[ps%2==0]
print(ps_eve)
print(ps_eve**2)

[ 2  4  6  8 10]
[  4  16  36  64 100]


In [15]:
# single line
print(ps)
ps[ps%2==0]**2

[ 2  3  4  5  6  7  8  9 10]


array([  4,  16,  36,  64, 100], dtype=int32)